// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD50J_FLaKKp4V90LXh0MIyyL4VRR-B4Gk',
    appId: '1:890654676062:web:05068b13dc139aed2810cf',
    messagingSenderId: '890654676062',
    projectId: 'app-tracker-3becf',
    authDomain: 'app-tracker-3becf.firebaseapp.com',
    storageBucket: 'app-tracker-3becf.firebasestorage.app',
    measurementId: 'G-D1PYM8B6J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGRHj450J9qz7NKc8FNgI9EVXz2bGtc7g',
    appId: '1:890654676062:android:b0053b33b45dfe0b2810cf',
    messagingSenderId: '890654676062',
    projectId: 'app-tracker-3becf',
    storageBucket: 'app-tracker-3becf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbrvAkpq7HTRfDaZ04VCs6gonj-m_OVv8',
    appId: '1:890654676062:ios:4734fc7d36f3967a2810cf',
    messagingSenderId: '890654676062',
    projectId: 'app-tracker-3becf',
    storageBucket: 'app-tracker-3becf.firebasestorage.app',
    iosBundleId: 'com.example.appTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbrvAkpq7HTRfDaZ04VCs6gonj-m_OVv8',
    appId: '1:890654676062:ios:4734fc7d36f3967a2810cf',
    messagingSenderId: '890654676062',
    projectId: 'app-tracker-3becf',
    storageBucket: 'app-tracker-3becf.firebasestorage.app',
    iosBundleId: 'com.example.appTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD50J_FLaKKp4V90LXh0MIyyL4VRR-B4Gk',
    appId: '1:890654676062:web:121f6b7631d7d8722810cf',
    messagingSenderId: '890654676062',
    projectId: 'app-tracker-3becf',
    authDomain: 'app-tracker-3becf.firebaseapp.com',
    storageBucket: 'app-tracker-3becf.firebasestorage.app',
    measurementId: 'G-8960NB5C21',
  );
}
